### ISSUE TITLE
culling exclusion zones far from player flight

### ISSUE THREAD

**Issue by HILOK** [dcs-retribution/dcs-retribution#419] opened 2024-11-20 12:20 UTC
### Affected versions

Test build

### Test/Development build

1468

### Description

culling exclusion zones encompass areas way outside player flight. intended as is or bug?
for info: player squad (harriers) used to be affiliated to LHA by campaign design. was transferred within campaign wizard to kiruna...maybe thats why?

### Save game and other files

![image](https://github.com/user-attachments/assets/159a7a02-92e8-49f2-b40f-27293a3b8957)
[state.json](https://github.com/user-attachments/files/17830319/state.json)

**Comment by Raffson** [comment] 2024-11-21 20:24
Could you show all flights on both sides? Normally a culling exclusion zone is created around every target that is part of an active flight-plan, so I think it's intended behavior 😅

**Comment by HILOK** [comment] 2024-11-22 09:21
sure, here you go.
![image](https://github.com/user-attachments/assets/63fa998e-3ca4-40b4-9ee2-314c933674bf)

**Comment by Raffson** [comment] 2024-11-23 03:15
Yeah so this sort of confirms what I said earlier, culling exclusion zones are not only for player flights, but for all flights.

**Comment by HILOK** [comment] 2024-11-23 10:08
ok i see, thanks. unfortunately it is currently stutter-wise unplayable on my system...

**Comment by Raffson** [comment] 2024-11-23 16:21
What specs are you running on? And are you running it as a dedicated server? Also, you can try removing some flights on both sides to ease up the load, which is probably going to be the most effective solution 😅

**Comment by HILOK** [comment] 2024-11-24 13:50
oh well, just an old i5 oc to 4.2GHz, so that's why. i am planning on running the campaign on a dedicated server, as soon as i get the chance. for the time being, i might have to tinker with reducing the number of units...thanks : )

**Comment by Raffson** [comment] 2024-11-24 15:51
Alright, will close this issue then.. feel free to continue the discussion in the performance channel of our discord 😉

**Closed as not planned by Raffson** 2024-11-24 15:51 UTC
Labels: Bug, Priority Medium
